version: '3'

services:
  piwik-db:
    image: mysql:5.7
    container_name: piwik-db
    ports:
      - "{db-external-port}:3306"
    volumes:
      - ./mysql/runtime:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: {db-pass}
    networks:
       - nginx
    restart: always
    deploy:
       resources:
         limits:
           cpus: '1.0'
           memory: 500m
  app:
    image: piwik:3.3.0-fpm
    container_name: piwik
    links:
      - piwik-db
    volumes:
      - ./html:/var/www/html
    environment:
       VIRTUAL_HOST: {virtual-host}
    networks:
       - nginx
    restart: always
    deploy:
       resources:
         limits:
           cpus: '1.0'
           memory: 200m

networks:
  nginx:
     external: true
