version: '2'

services:
  db:
    image: mysql:5.7
    ports:
      - "{port to map}:3306"
    volumes:
      - ./mysql/runtime:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: secret
    network_mode: "bridge"
    restart: always
  app:
    image: piwik:3.0
    links:
      - db
    volumes:
      - ./html:/var/www/html
    environment:
       VIRTUAL_HOST: {your virtual host :-)}
    network_mode: "bridge"
    restart: always
  cron:
    image: piwik
    links:
      - db
    volumes_from:
      - app
    entrypoint: |
      bash -c 'bash -s <<EOF
      trap "break;exit" SIGHUP SIGINT SIGTERM
      while /bin/true; do
        su -s "/bin/bash" -c "/usr/local/bin/php /var/www/html/console core:archive" www-data
        sleep 3600
      done
      EOF'
    network_mode: "bridge"
    restart: always
